version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: rack-mini-profiler
    versions:
    - 2.3.0
  - dependency-name: webpacker
    versions:
    - 5.2.1
