version: '2'
services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db:
    driver: local
