version: '2'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/songforge
    tty: true
    stdin_open: true
    command: bin/rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - docker.env
volumes:
  db:
    driver: local
