version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/songforge
    ports:
      - "3000:3000"
    depends_on:
      - db
