version: '2'
services:
  db:
    image: postgres
  web: &app_base
    build: .
    volumes:
      - .:/songforge
    tty: true
    stdin_open: true
    command: bin/rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack
  webpack:
    <<: *app_base
    command: bin/webpack-dev-server
    ports:
      - "3035:3035"
    depends_on:
      - db
