version: 2
  jobs:
    build:
      working_directory: ~/workspace
      docker:
        - image: ruby:2.4.0
        - image: postgres
      environment:
        PHANTOMJS_URL: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
      steps:
        - checkout
        - type: cache-restore
          key: phantomjs-2.1.1
        - type: cache-restore
          key: gemfile-{{ checksum "Gemfile.lock" }}
        - run: |
            which phantomjs && exit
            curl --location --silent $PHANTOMJS_URL | tar xj -C /tmp --strip-components=1
            mv /tmp/bin/phantomjs /bin
        - run: apt-get update -qq && apt-get install -y build-essential nodejs
        - run: bin/setup
        - run: bin/rspec
        - type: cache-save
          key: phantomjs-2.1.1
          paths:
            - /bin/phantomjs
        - type: cache-save
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bundle
